### ISSUE TITLE
[Error: Erro: read failed, socket might closed or timeout, read ret: -1]

### ISSUE THREAD

**Issue by TimosValais** [renancsoares/react-native-datecs-printer#19]
Hello sorry to bother you, I get this error when I try to connect to a printer (I'm using the app example that you give). Any idea what could be at fault would be really helpful thank you in advance! (I have paired a datecs dpp-250 to my mobile which I use through android studio, I don't know what other info to give, I 've done the installation step by step, any other info you might need feel free to ask thank you again).

**Comment by recs182** [comment]
Hello @TimosValais, no worries!

It is a really long time since I last interacted with this project or the application that used it. I would highly encourage you to fork this project to improve and update its code to be better inspected at least.

I could make the changes but I do not have android studio installed nor use react-native in a long time. I don't know how it evolved during the last almost 4 years.

---

About your problem it could be anything from not being able to get bonded devices, create the socket streams or even create the Thread. The code is really bad as it does not make clear were it breaks, I should have know better when I created this.

I will include below what I think is the fault block code, that is all this first block inside the try/catch.
https://github.com/recs182/react-native-datecs-printer/blob/ac612123af2cf8b4f5945d643cb00a2d9c9fb64d/android/src/main/java/com/renancsoares/datecsprinter/RNDatecsPrinterModule.java#L151-L225

**Comment by TimosValais** [comment]
Hello! No worries your code has been helpful, from what I researched it must be this line : 
mmSocket = mmDevice.createRfcommSocketToServiceRecord(uuid); 
 because that gives a -1 value by default. A workaround for whomever wants it is this : 
```java
                try {

mmSocket =(BluetoothSocket) mmDevice.getClass().getMethod("createRfcommSocket", new Class[] {int.class}).invoke(mmDevice,1);
mmSocket.connect();
                   
                }
             catch (Exception e2) {
                showToast(e2.getMessage());
```
It hasn't worked yet for me but I 'm not losing my hope! 

Again thank you for your time, I should have seen that the project was completed so long ago, so thank you for answering!

**Comment by TimosValais** [comment]
Just letting anyone who might find this in the future (greetings from 2021, hasn't been a great year so far hope you 're doing better than us as a whole :P ) that I found my issue. It was with this line : 

mmDevice = (BluetoothDevice) list.get(0);

Basically what was happening was that I had my phone paired with other devices (like my jbl speaker) so get(0) was not bringing the printer. I have two workarounds that I'll work on, depending on my deadline, the one is to add only if device.getName() starts with "dpp" because that's the printer I'm working on and it's good enough for now but the best solution would be to bring the list of the paired devices and have the user pick which one to pass as a parameter to the connect function. 

Thank you again for your time, if I have time in the future I will fork this and present my solution!

**Comment by recs182** [comment]
Makes sense and your solution would be awesome, If I recall correctly it wasn't made this way because we would never have multiple devices paired but probably 4 years later I would have done things better.

Hope you can solve the issue and move forward with your project.
