### ISSUE TITLE
Printing function not printing bulgarian language

### ISSUE THREAD

**Issue by vtassev** [renancsoares/react-native-datecs-printer#3]
When I'm trying to print something like this all of the bulgarian characters are printed as question marks
My code for printing looks like this:

```this.print(`{center}Адрес:${params.title} {br} Апартамент номер:${params.apartment} {br} Клиентски номер:${params.client_id?params.client_id:0} {br} Платено от:${params.contact_person} {br} Платено: ${params.monthly_fee} {br} За период: {br} ${params.from_date} - ${params.to_date} `)}```

**Comment by recs182** [comment]
I only imagine that this could be some kind of charset problem since it's only printing question marks as you said.

The default charset is `ISO-8859-1` in the **RNDatecsPrinterModule.java** file, you could try to modify this to see if it works.

I don't have a printer anymore to make tests but I think I could add the possibility to pass the charset as an argument when I have some spare time.
